### PR TITLE
added initializeDate option

### PR DESCRIPTION
**Pull request by AndreasSoiron**
I needed to initialize the date picker with another date than now so i added this option.

### CODE REVIEW

**Comment by tazsingh** [comment]
will_pickdate will actually initialize from the value of the input element it is bound to. If you set the input's value in accordance with your `inputOutputFormat`, it should just work.

**Comment by kaonL0** [comment]
Hi,
I think this add can be usefull and I came here to talk about that and submit this change.
In my case I want the users pick a date by itself without seeing any value in the component.
In our app this date is not the date of the day (cause it is a form for inscription to an event), so by default it will be more confortable if the date is the start of the event. 
I think now we can't do that.

**Comment by tanema** [comment]
if no initializeDate is given will it still parse the date in the input, also what happens when an initializeDate is given but there is also a value in the input?
~~I do not have time to go through the code right now, if you handled these cases correctly I will have a look and and see if I can pull your changes.~~ (This is not the repo I thought it was Sorry Taz!)

**Comment by AndreasSoiron** [comment]
Hi,
@kaonL0 did you mean that you want to have an empty textfield wich opens the datepicker with the initializeDate?
if I was right, you can reach this by setting the initializeDate as a unix timestamp and set the allowEmpty method on true.
@tanema yes it will parse the given date and if both are set it will take the value from the input

**Comment by kaonL0** [comment]
I just discover github, so i try my best to anderstand who it works ;) and to contribute correctly !
@AndreasSoiron yes you right, and when the user choose a date, it have to fill the input, after as you told it, the component have to use the filled value. So i think your add could be used, no ?
@tanema what do you think ?

**Comment by tazsingh** [comment]
Hi Guys,

Thanks for the discussion. If I'm understanding you all correctly, you'd like will_pickdate to open at a date other than whatever is set in the input field?

To put it another way, setting the input field's value and then attaching `will_pickdate` to it won't work because you'd like the field to be empty if a value isn't set?

**Comment by kaonL0** [comment]
Hi
@tazsingh 1) only if the input filed if empty, 2) so yes, and i should add, isn't set by the user :)

**Comment by tazsingh** [comment]
Ok that's a good reason for this feature. I'll take a look at the pull request when I have a moment before the end of the week and make any changes if necessary. (It's been a while since I've looked at this code!)

@tanema, if you would still like to take a look, feedback would be great. Also if you've been having any issues with my date picker, this would be the place to report them.

**Comment by kaonL0** [comment]
Thx, if i can do something (excepetd test, i'll do), plz ask

**Comment by tazsingh** [comment]
@tanema (Seeing your strikeout comment now) No problem! Just remember that this is the main repo and it would be nice if [these issues](https://github.com/zenapsis/will_pickdate/issues?direction=desc&sort=created&state=open) were reported here to keep things centralized and consistent. Unless you guys are planning on submitting a pull request of course :)

**Comment by tanema** [comment]
Yeah I will probably do a pull request I just really put those there as a reminder to address them later however if you are willing to look into those issues I will log them here and you can address them as well.

**Comment by tazsingh** [comment]
Of course I'd be willing to look at issues!

**Pull request closed without merging**
